name: Kanban automation (classic Project)

on:
  issues:
    types: [opened]
  create:
    # branch creation is filtered in the job with an if condition
  pull_request:
    types: [opened, closed]
  push:
    branches: [develop]

permissions:
  contents: read
  issues: write
  pull-requests: read
  repository-projects: read

jobs:
  kanban-sync:
    runs-on: ubuntu-latest
    steps:
      - name: 이슈 생성 시 백로그로 등록
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: ./.github/actions/kanban-management/add-to-backlog
        with:
          org: modern-agile-team
          project-number: 55
          project-name: zoop-admin 작업 목록
          backlog: 백로그
          planned: 작업 예정
          in-progress: 작업중
          review: 리뷰 대기
          done: 완료
          github-token: ${{ secrets.ORG_PROJECTS_TOKEN != '' && secrets.ORG_PROJECTS_TOKEN || github.token }}

      - name: 브랜치 생성 시 작업중으로 변경
        if: github.event_name == 'create' && github.event.ref_type == 'branch'
        uses: ./.github/actions/kanban-management/transition-on-branch
        with:
          org: modern-agile-team
          project-number: 55
          project-name: zoop-admin 작업 목록
          backlog: 백로그
          planned: 작업 예정
          in-progress: 작업중
          review: 리뷰 대기
          done: 완료
          github-token: ${{ secrets.ORG_PROJECTS_TOKEN != '' && secrets.ORG_PROJECTS_TOKEN || github.token }}

      - name: PR 오픈 시 리뷰 대기로 변경
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        uses: ./.github/actions/kanban-management/transition-on-pr
        with:
          mode: opened
          org: modern-agile-team
          project-number: 55
          project-name: zoop-admin 작업 목록
          backlog: 백로그
          planned: 작업 예정
          in-progress: 작업중
          review: 리뷰 대기
          done: 완료
          github-token: ${{ secrets.ORG_PROJECTS_TOKEN != '' && secrets.ORG_PROJECTS_TOKEN || github.token }}

      - name: PR 머지 시 완료로 변경
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: ./.github/actions/kanban-management/transition-on-pr
        with:
          mode: merged
          org: modern-agile-team
          project-number: 55
          project-name: zoop-admin 작업 목록
          backlog: 백로그
          planned: 작업 예정
          in-progress: 작업중
          review: 리뷰 대기
          done: 완료
          github-token: ${{ secrets.ORG_PROJECTS_TOKEN != '' && secrets.ORG_PROJECTS_TOKEN || github.token }}

      - name: develop 푸시 시 완료로 변경
        if: github.event_name == 'push'
        uses: ./.github/actions/kanban-management/transition-on-develop
        with:
          org: modern-agile-team
          project-number: 55
          project-name: zoop-admin 작업 목록
          backlog: 백로그
          planned: 작업 예정
          in-progress: 작업중
          review: 리뷰 대기
          done: 완료
          github-token: ${{ secrets.ORG_PROJECTS_TOKEN != '' && secrets.ORG_PROJECTS_TOKEN || github.token }}
