name: PR Template Auto Fill

on:
  pull_request:
    types: [opened] # PR이 생성될 때만 실행

permissions:
  pull-requests: write
  contents: read

jobs:
  auto-fill-pr-template:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Node.js 환경 설정
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      # 3️⃣ 필요한 패키지 설치 (fetch 등)
      - name: Install dependencies
        run: npm install

      # 4️⃣ 스크립트 실행
      - name: Run auto issue fill script
        run: node .github/scripts/pr-auto-issue-fill.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
