name: prod 환경 릴리즈

on:
  push:
    branches: [main]

env:
  IMAGE: ghcr.io/modern-agile-team/zoop-admin-front
  APP: zoop-admin-front

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "Extracted version from package.json: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: PR 생성 후 머지 (release/${{ steps.version.outputs.VERSION }} -> develop)
        env:
          TITLE: Merge '${{ steps.version.outputs.VERSION }}' into develop
          BODY: |
            Merge tag '${{ steps.version.outputs.VERSION }}' into develop.

            > This PR was created automatically for up-to-date develop branch and will merge immediately.
        run: |
          gh pr create --head $MAIN_BRANCH --base $BASE_BRANCH --title "$TITLE" --body "$BODY"
          gh pr merge $MAIN_BRANCH --merge

  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: prod
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
      - name: clean yarn cache
        run: yarn cache clean
      - name: Install & Build
        shell: bash
        run: |
          yarn install
          VITE_APP_ENV=prod \
          VITE_API_URL='${{ vars.VITE_API_URL }}' \
          yarn build:prod
          mkdir -p releases && mv dist releases/build
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            APP_PORT=${{ vars.VITE_APP_PORT }}
          tags: |
            ${{ env.IMAGE }}:latest-prod
            ${{ env.IMAGE }}:prod-${{ github.sha }}

  deploy:
    needs: [build-and-push]
    runs-on: self-hosted
    environment:
      name: prod
    permissions:
      contents: read
      packages: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull & Resolve
        id: r
        run: |
          I=${{ env.IMAGE }}:latest-prod
          docker pull "$I"
          echo "image=$(docker inspect --format='{{index .RepoDigests 0}}' $I)" >> $GITHUB_OUTPUT
      - name: Run
        env:
          NAME: ${{ env.APP }}-prod
          PORT: ${{ vars.VITE_APP_PORT }}
        run: |
          docker rm -f "$NAME" || true
          docker run -d --name "$NAME" --restart unless-stopped \
            -e PORT="$PORT" -p "$PORT:$PORT" "${{ steps.r.outputs.image }}"
      - run: docker image prune -f
